//go:build !windows

package phpver

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"pm/internal/archive"
	"pm/internal/download"
	"pm/internal/pmdir"
)

// PhpFpmName is the FastCGI server binary that serves sites off Windows
// (the static builds ship no php-cgi; php-fpm is the platform standard).
const PhpFpmName = "php-fpm"

// Install downloads the static cli and fpm binaries into
// ~/.mullion/php/<version> and writes a working php.ini. It is a no-op if
// the version is already installed.
func Install(ctx context.Context, paths pmdir.Paths, rel Release) (string, error) {
	destDir := paths.PhpVersionDir(rel.Version)
	_, errCli := os.Stat(filepath.Join(destDir, PhpExeName))
	_, errFpm := os.Stat(filepath.Join(destDir, PhpFpmName))
	if errCli == nil && errFpm == nil {
		return destDir, nil
	}

	fmt.Printf("Downloading PHP %s...\n", rel.Version)
	for _, url := range []string{rel.ZipURL, rel.FpmURL} {
		tarPath := filepath.Join(paths.TmpDir(), filepath.Base(url))
		if err := download.ToFile(ctx, url, tarPath); err != nil {
			return "", err
		}
		if err := archive.ExtractTarGz(tarPath, destDir); err != nil {
			os.Remove(tarPath)
			os.RemoveAll(destDir)
			return "", fmt.Errorf("extracting %s: %w", tarPath, err)
		}
		os.Remove(tarPath)
	}
	for _, bin := range []string{PhpExeName, PhpFpmName} {
		if err := os.Chmod(filepath.Join(destDir, bin), 0o755); err != nil {
			return "", fmt.Errorf("PHP %s: unexpected archive layout: %w", rel.Version, err)
		}
	}
	if err := writeIni(destDir); err != nil {
		return "", fmt.Errorf("writing php.ini: %w", err)
	}
	return destDir, nil
}

// writeIni creates a development php.ini from scratch — the static
// builds ship none, and every extension they know is compiled in.
func writeIni(phpDir string) error {
	iniPath := filepath.Join(phpDir, "php.ini")
	if _, err := os.Stat(iniPath); err == nil {
		return nil
	}
	var b strings.Builder
	b.WriteString("; Generated by mullion — safe to edit; recreated only if deleted.\n")
	b.WriteString("; This is a static PHP build: all its extensions are compiled in.\n\n")
	b.WriteString("display_errors=On\n")
	b.WriteString("display_startup_errors=On\n")
	b.WriteString("error_reporting=E_ALL\n")
	b.WriteString("opcache.enable=1\n")
	b.WriteString("cgi.fix_pathinfo=1\n")
	b.WriteString("memory_limit=512M\n")
	b.WriteString("upload_max_filesize=100M\n")
	b.WriteString("post_max_size=100M\n")
	b.WriteString("max_execution_time=120\n")

	// The static openssl/curl need to be told where the system CA bundle is.
	for _, ca := range []string{
		"/etc/ssl/cert.pem",                  // macOS
		"/etc/ssl/certs/ca-certificates.crt", // Debian/Ubuntu
		"/etc/pki/tls/certs/ca-bundle.crt",   // Fedora/RHEL
	} {
		if _, err := os.Stat(ca); err == nil {
			b.WriteString("curl.cainfo=\"" + ca + "\"\n")
			b.WriteString("openssl.cafile=\"" + ca + "\"\n")
			break
		}
	}
	return os.WriteFile(iniPath, []byte(b.String()), 0o644)
}
