//go:build !windows

package fcgi

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"syscall"

	"pm/internal/phpver"
	"pm/internal/pmdir"
)

// workerCmd builds the php-fpm command that serves one version's port —
// the static builds ship php-fpm instead of php-cgi, and Caddy's
// php_fastcgi speaks to both the same way.
func workerCmd(paths pmdir.Paths, version string, port int) (*exec.Cmd, error) {
	dir := paths.PhpVersionDir(version)
	exe := filepath.Join(dir, phpver.PhpFpmName)
	if _, err := os.Stat(exe); err != nil {
		return nil, fmt.Errorf("php-fpm not found for %s: %w", version, err)
	}
	conf, err := writeFpmConf(paths, version, port)
	if err != nil {
		return nil, err
	}
	// -F keeps the master in the foreground (we detach it ourselves, so
	// the pid we record is the master's), -y/-c pin the config files.
	return exec.Command(exe, "-F", "-y", conf, "-c", filepath.Join(dir, "php.ini")), nil
}

// writeFpmConf (re)generates the pool config for one version branch.
func writeFpmConf(paths pmdir.Paths, version string, port int) (string, error) {
	sel, err := phpver.ParseSelector(version)
	if err != nil {
		return "", err
	}
	conf := filepath.Join(paths.PhpDir(), fmt.Sprintf("fpm-%d.%d.conf", sel.Major, sel.Minor))
	content := fmt.Sprintf(`; Generated by mullion — do not edit; changes are overwritten.
[global]
error_log = %s
daemonize = no

[www]
listen = 127.0.0.1:%d
pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4
catch_workers_output = yes
clear_env = no
`, filepath.Join(paths.LogsDir(), fmt.Sprintf("php-fpm-%d.%d.log", sel.Major, sel.Minor)), port)
	return conf, os.WriteFile(conf, []byte(content), 0o644)
}

// killWorker terminates the fpm master AND its pool: the master runs as
// its own process-group leader (proc.Detach uses Setsid), so signalling
// the group takes the workers down with it — a bare SIGKILL on the
// master would leak workers that keep holding the port.
func killWorker(pid int) {
	if err := syscall.Kill(-pid, syscall.SIGTERM); err != nil {
		_ = syscall.Kill(pid, syscall.SIGTERM)
	}
}
