// Package phpmyadmin installs phpMyAdmin into ~/.mullion/phpmyadmin and
// writes a config that auto-connects to the local MySQL server.
package phpmyadmin

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"pm/internal/archive"
	"pm/internal/download"
	"pm/internal/pmdir"
)

// The project publishes a stable alias for the newest release.
const latestZipURL = "https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.zip"

// Install downloads and unpacks phpMyAdmin ("" = latest release) and
// writes config.inc.php. With no version requested it is a no-op when
// already installed; a specific version always replaces the current one.
func Install(ctx context.Context, paths pmdir.Paths, version string) error {
	dir := paths.PhpMyAdminDir()
	if version == "" {
		if _, err := os.Stat(filepath.Join(dir, "index.php")); err == nil {
			return ensureConfig(dir)
		}
	}

	url := latestZipURL
	if version != "" {
		url = fmt.Sprintf("https://files.phpmyadmin.net/phpMyAdmin/%s/phpMyAdmin-%s-all-languages.zip", version, version)
	}
	zipPath := filepath.Join(paths.TmpDir(), "phpmyadmin.zip")
	fmt.Println("Downloading phpMyAdmin...")
	if err := download.ToFile(ctx, url, zipPath); err != nil {
		return err
	}
	defer os.Remove(zipPath)

	// The zip wraps everything in a phpMyAdmin-<v>-all-languages/
	// directory: extract to a staging dir, then move it into place.
	staging := filepath.Join(paths.TmpDir(), "phpmyadmin-extract")
	os.RemoveAll(staging)
	if err := archive.ExtractZip(zipPath, staging); err != nil {
		return fmt.Errorf("extracting %s: %w", zipPath, err)
	}
	inner, err := findInner(staging)
	if err != nil {
		return err
	}
	os.RemoveAll(dir)
	if err := os.Rename(inner, dir); err != nil {
		return err
	}
	os.RemoveAll(staging)
	return ensureConfig(dir)
}

func findInner(staging string) (string, error) {
	entries, err := os.ReadDir(staging)
	if err != nil {
		return "", err
	}
	for _, e := range entries {
		if e.IsDir() && strings.HasPrefix(e.Name(), "phpMyAdmin-") {
			return filepath.Join(staging, e.Name()), nil
		}
	}
	return "", fmt.Errorf("unexpected archive layout: no phpMyAdmin-* directory in %s", staging)
}

// ensureConfig writes config.inc.php (auto-login as root on the local
// server, matching mysqld's --initialize-insecure setup) and the temp
// dir phpMyAdmin wants to cache templates in.
func ensureConfig(dir string) error {
	if err := os.MkdirAll(filepath.Join(dir, "tmp"), 0o755); err != nil {
		return err
	}
	confPath := filepath.Join(dir, "config.inc.php")
	if _, err := os.Stat(confPath); err == nil {
		return nil
	}

	secret := make([]byte, 32)
	if _, err := rand.Read(secret); err != nil {
		return err
	}
	conf := fmt.Sprintf(`<?php
// Generated by mullion — safe to edit; recreated only if deleted.
declare(strict_types=1);

$cfg['blowfish_secret'] = '%s';

$i = 1;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['AllowNoPassword'] = true;

$cfg['TempDir'] = __DIR__ . '/tmp';
`, hex.EncodeToString(secret))
	return os.WriteFile(confPath, []byte(conf), 0o644)
}
