// Package phpmyadmin installs phpMyAdmin into ~/.mullion/phpmyadmin and
// writes a config that auto-connects to the local MySQL server.
package phpmyadmin

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"pm/internal/archive"
	"pm/internal/download"
	"pm/internal/mysql"
	"pm/internal/pmdir"
)

// The project publishes a stable alias for the newest release.
const latestZipURL = "https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.zip"

// Install downloads and unpacks phpMyAdmin ("" = latest release) and
// writes config.inc.php. With no version requested it is a no-op when
// already installed; a specific version always replaces the current one.
func Install(ctx context.Context, paths pmdir.Paths, version, mysqlPassword string) error {
	dir := paths.PhpMyAdminDir()
	if version == "" {
		if _, err := os.Stat(filepath.Join(dir, "index.php")); err == nil {
			return ensureConfig(dir, mysqlPassword)
		}
	}

	url := latestZipURL
	if version != "" {
		url = fmt.Sprintf("https://files.phpmyadmin.net/phpMyAdmin/%s/phpMyAdmin-%s-all-languages.zip", version, version)
	}
	zipPath := filepath.Join(paths.TmpDir(), "phpmyadmin.zip")
	fmt.Println("Downloading phpMyAdmin...")
	if err := download.ToFile(ctx, url, zipPath); err != nil {
		return err
	}
	defer os.Remove(zipPath)

	// The zip wraps everything in a phpMyAdmin-<v>-all-languages/
	// directory: extract to a staging dir, then move it into place.
	staging := filepath.Join(paths.TmpDir(), "phpmyadmin-extract")
	os.RemoveAll(staging)
	if err := archive.ExtractZip(zipPath, staging); err != nil {
		return fmt.Errorf("extracting %s: %w", zipPath, err)
	}
	inner, err := findInner(staging)
	if err != nil {
		return err
	}
	os.RemoveAll(dir)
	if err := os.Rename(inner, dir); err != nil {
		return err
	}
	os.RemoveAll(staging)
	return ensureConfig(dir, mysqlPassword)
}

func findInner(staging string) (string, error) {
	entries, err := os.ReadDir(staging)
	if err != nil {
		return "", err
	}
	for _, e := range entries {
		if e.IsDir() && strings.HasPrefix(e.Name(), "phpMyAdmin-") {
			return filepath.Join(staging, e.Name()), nil
		}
	}
	return "", fmt.Errorf("unexpected archive layout: no phpMyAdmin-* directory in %s", staging)
}

// ensureConfig writes config.inc.php when missing — or when it points at
// a different MySQL port than the server's current one (mysql.Port).
func ensureConfig(dir, mysqlPassword string) error {
	if err := os.MkdirAll(filepath.Join(dir, "tmp"), 0o755); err != nil {
		return err
	}
	if b, err := os.ReadFile(filepath.Join(dir, "config.inc.php")); err == nil &&
		strings.Contains(string(b), portLine(mysql.Port)) {
		return nil
	}
	return writeConfig(dir, mysqlPassword)
}

// portLine is config.inc.php's server-port setting.
func portLine(port int) string {
	return "$cfg['Servers'][$i]['port'] = '" + strconv.Itoa(port) + "';"
}

// RefreshConfig rewrites config.inc.php so phpMyAdmin follows a changed
// MySQL root password or port (mysql.Port). No-op when phpMyAdmin isn't
// installed.
func RefreshConfig(paths pmdir.Paths, mysqlPassword string) error {
	dir := paths.PhpMyAdminDir()
	if _, err := os.Stat(filepath.Join(dir, "index.php")); err != nil {
		return nil
	}
	if err := os.MkdirAll(filepath.Join(dir, "tmp"), 0o755); err != nil {
		return err
	}
	return writeConfig(dir, mysqlPassword)
}

// writeConfig generates config.inc.php: auto-login as root with the
// current password, so the browser lands straight in phpMyAdmin.
func writeConfig(dir, mysqlPassword string) error {
	secret := make([]byte, 32)
	if _, err := rand.Read(secret); err != nil {
		return err
	}
	conf := renderConfig(hex.EncodeToString(secret), mysqlPassword, mysql.Port)
	return os.WriteFile(filepath.Join(dir, "config.inc.php"), []byte(conf), 0o644)
}

// renderConfig is config.inc.php's content.
func renderConfig(secret, mysqlPassword string, port int) string {
	pwd := strings.ReplaceAll(mysqlPassword, `\`, `\\`)
	pwd = strings.ReplaceAll(pwd, "'", `\'`)
	return fmt.Sprintf(`<?php
// Generated by mullion — recreated when settings change (e.g. the MySQL
// root password); put custom settings in a separate config if needed.
declare(strict_types=1);

$cfg['blowfish_secret'] = '%s';

$i = 1;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
%s
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '%s';
$cfg['Servers'][$i]['AllowNoPassword'] = %s;

$cfg['TempDir'] = __DIR__ . '/tmp';
`, secret, portLine(port), pwd, allowNoPassword(mysqlPassword))
}

func allowNoPassword(password string) string {
	if password == "" {
		return "true"
	}
	return "false"
}

// Installed reports whether phpMyAdmin's files are present.
func Installed(paths pmdir.Paths) bool {
	_, err := os.Stat(filepath.Join(paths.PhpMyAdminDir(), "index.php"))
	return err == nil
}

// Remove deletes Mullion's phpMyAdmin install. It does not unlink the
// "phpmyadmin" site or touch MySQL — callers that need the whole
// teardown (e.g. `mullion phpmyadmin uninstall`) do that separately.
func Remove(paths pmdir.Paths) error {
	return os.RemoveAll(paths.PhpMyAdminDir())
}
