// Package macapp installs and removes the native macOS "Mullion.app"
// window host. The app bundle itself (a gzipped tar of Mullion.app,
// built from macapp/) is generated by `bash macapp/build.sh` into
// bundle/Mullion.app.tar.gz and embedded below; that file is
// gitignored; a placeholder README.md is committed in its place so
// go:embed always has a match and builds without it still compile.
package macapp

import "embed"

//go:embed bundle
var bundleFS embed.FS

// tarballPath is bundleFS's path to the embedded app bundle.
const tarballPath = "bundle/Mullion.app.tar.gz"

// Available reports whether this build has the Mac app bundle
// embedded (i.e. macapp/build.sh ran before `go build`).
func Available() bool {
	f, err := bundleFS.Open(tarballPath)
	if err != nil {
		return false
	}
	f.Close()
	return true
}
