// Package caddy generates the Caddyfile and controls the Caddy process
// that serves every linked site.
package caddy

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// SiteConf is everything the Caddyfile needs to know about one site.
type SiteConf struct {
	Host     string // e.g. "blog.test"
	Root     string // absolute document root
	FcgiPort int    // php-cgi port for this site's PHP version
	Secure   bool
}

// Generate renders the full Caddyfile. Secured sites use Caddy's internal
// CA (locally-trusted certificates); the rest are served over plain HTTP.
func Generate(sites []SiteConf, logsDir string) string {
	var b strings.Builder
	b.WriteString("# Generated by mullion — do not edit; changes are overwritten.\n")
	// No skip_install_trust here: Caddy's Caddyfile adapter treats it as a
	// bare flag and ignores its argument, so `skip_install_trust false`
	// would actually DISABLE installing the root CA into the trust store.
	b.WriteString("{\n\tadmin 127.0.0.1:2019\n\tlocal_certs\n}\n")

	for _, s := range sites {
		addr := s.Host
		if !s.Secure {
			addr = "http://" + s.Host
		}
		b.WriteString("\n" + addr + " {\n")
		b.WriteString("\troot * " + quote(s.Root) + "\n")
		if s.Secure {
			b.WriteString("\ttls internal\n")
		}
		b.WriteString("\tencode zstd gzip\n")
		b.WriteString(fmt.Sprintf("\tphp_fastcgi 127.0.0.1:%d\n", s.FcgiPort))
		b.WriteString("\tfile_server\n")
		b.WriteString("\tlog {\n\t\toutput file " + quote(filepath.Join(logsDir, s.Host+".log")) + "\n\t}\n")
		b.WriteString("}\n")
	}
	return b.String()
}

// DocRoot picks the directory Caddy should serve for a project: public/
// when it contains an index.php (Laravel & friends), else the project root.
func DocRoot(projectPath string) string {
	public := filepath.Join(projectPath, "public")
	if _, err := os.Stat(filepath.Join(public, "index.php")); err == nil {
		return public
	}
	return projectPath
}

func quote(s string) string {
	return `"` + strings.ReplaceAll(s, `\`, `\\`) + `"`
}
