// Package caddy generates the Caddyfile and controls the Caddy process
// that serves every linked site.
package caddy

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// SiteConf is everything the Caddyfile needs to know about one site.
type SiteConf struct {
	Host      string // e.g. "blog.test"
	Kind      string // "php" (default), "node", or "static"
	Root      string // absolute document root (php and static sites)
	FcgiPort  int    // FastCGI port for this site's PHP version
	ProxyPort int    // dev-server port for node sites (0 = not running)
	// RewriteHost makes the proxy send "localhost:<port>" as the Host
	// header — Vite-family dev servers block unknown hosts (and old
	// versions ignore the allow-list env var), but always accept
	// localhost. Only set for Vite projects: others (Next.js) rely on
	// the original Host for origin checks.
	RewriteHost bool
	Paused      bool // the user stopped this dev server on purpose
	Secure      bool
}

// Generate renders the full Caddyfile. Secured sites use Caddy's internal
// CA (locally-trusted certificates); the rest are served over plain HTTP.
func Generate(sites []SiteConf, logsDir string) string {
	var b strings.Builder
	b.WriteString("# Generated by mullion — do not edit; changes are overwritten.\n")
	// No skip_install_trust here: Caddy's Caddyfile adapter treats it as a
	// bare flag and ignores its argument, so `skip_install_trust false`
	// would actually DISABLE installing the root CA into the trust store.
	b.WriteString("{\n\tadmin 127.0.0.1:2019\n\tlocal_certs\n}\n")

	for _, s := range sites {
		addr := s.Host
		if !s.Secure {
			addr = "http://" + s.Host
		}
		b.WriteString("\n" + addr + " {\n")
		if s.Secure {
			b.WriteString("\ttls internal\n")
		}
		switch s.Kind {
		case "node":
			if s.ProxyPort > 0 {
				// localhost (not 127.0.0.1): dev servers often listen on
				// ::1 only, and dialing localhost covers both families.
				if s.RewriteHost {
					b.WriteString(fmt.Sprintf("\treverse_proxy localhost:%d {\n\t\theader_up Host {upstream_hostport}\n\t}\n", s.ProxyPort))
				} else {
					b.WriteString(fmt.Sprintf("\treverse_proxy localhost:%d\n", s.ProxyPort))
				}
			} else if s.Paused {
				b.WriteString("\trespond \"This site's dev server is paused — start it from the Mullion panel or with `mullion dev start`.\" 503\n")
			} else {
				b.WriteString("\trespond \"The dev server for this site is not running — run `mullion start` (or open the Mullion panel).\" 503\n")
			}
		case "static":
			b.WriteString("\troot * " + quote(s.Root) + "\n")
			b.WriteString("\tencode zstd gzip\n")
			// Single-page apps route in the browser: unknown paths fall
			// back to index.html.
			b.WriteString("\ttry_files {path} /index.html\n")
			b.WriteString("\tfile_server\n")
		default: // php
			b.WriteString("\troot * " + quote(s.Root) + "\n")
			b.WriteString("\tencode zstd gzip\n")
			b.WriteString(fmt.Sprintf("\tphp_fastcgi 127.0.0.1:%d\n", s.FcgiPort))
			b.WriteString("\tfile_server\n")
		}
		b.WriteString("\tlog {\n\t\toutput file " + quote(filepath.Join(logsDir, s.Host+".log")) + "\n\t}\n")
		b.WriteString("}\n")
	}
	return b.String()
}

// DocRoot picks the directory Caddy should serve for a project: public/
// when it contains an index.php (Laravel & friends), else the project root.
func DocRoot(projectPath string) string {
	public := filepath.Join(projectPath, "public")
	if _, err := os.Stat(filepath.Join(public, "index.php")); err == nil {
		return public
	}
	return projectPath
}

func quote(s string) string {
	return `"` + strings.ReplaceAll(s, `\`, `\\`) + `"`
}
