//go:build !windows

package cmd

import (
	"os"
	"path/filepath"
)

// writeNodeShims puts node/npm/npx/corepack shims into bin — the
// directory that leads the PATH — so every terminal invocation resolves
// through Mullion and gets the RIGHT version for the current project
// (pinned site version → .nvmrc → global default).
func writeNodeShims(binDir string) error {
	for _, tool := range []string{"node", "npm", "npx", "corepack"} {
		shim := `#!/bin/sh
# Generated by mullion — resolves the Node version for the current project.
bin="$("$(dirname "$0")/mullion" node bin ` + tool + `)" || exit 1
exec "$bin" "$@"
`
		if err := os.WriteFile(filepath.Join(binDir, tool), []byte(shim), 0o755); err != nil {
			return err
		}
	}
	return nil
}
