//go:build windows

package cmd

import (
	"os"
	"path/filepath"
)

// writeNodeShims puts node/npm/npx/corepack shims into bin so every
// terminal invocation resolves through Mullion and gets the RIGHT
// version for the current project (pinned site → .nvmrc → global).
func writeNodeShims(binDir string) error {
	for _, tool := range []string{"node", "npm", "npx", "corepack"} {
		shim := "@echo off\r\n" +
			"rem Generated by mullion — resolves the Node version for the current project.\r\n" +
			"for /f \"delims=\" %%i in ('\"%~dp0mullion.exe\" node bin " + tool + "') do set \"MULLION_NODE_BIN=%%i\"\r\n" +
			"if not defined MULLION_NODE_BIN exit /b 1\r\n" +
			"\"%MULLION_NODE_BIN%\" %*\r\n"
		if err := os.WriteFile(filepath.Join(binDir, tool+".cmd"), []byte(shim), 0o755); err != nil {
			return err
		}
	}
	return nil
}
